#ifndef _WEBASSEMBLYINTRINSICTESTS_H
#define _WEBASSEMBLYINTRINSICTESTS_H 1

typedef int (*UNIT_TEST_FUNCTION) ();

//need to enumerate errors better
#define WASM_TEST_SUCCESS 0
#define NUMBER_OF_TESTS 1
#define WASM_TEST_GENERAL_FAIL -NUMBER_OF_TESTS

#endif